/* Science Lab Simulator V3 — unified, student-facing engine */
(()=>{"use strict";
const E=window.EXPERIMENTS||[],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="sls-v3-state";
let store;try{store=JSON.parse(localStorage.getItem(KEY))||{attempts:{},xp:0}}catch{store={attempts:{},xp:0}};
let current=E[0],S=null,timer=null;
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const apparatusIcons={"power supply":"⚡","dc power supply":"⚡","battery":"🔋","ammeter":"A","voltmeter":"V","resistor":"▰","connecting wires":"╱","wire":"╱","balance":"⚖","measuring cylinder":"▥","vernier calipers":"⌐","micrometer":"⌀","ruler":"📏","meter rule":"📏","spring":"〰","masses":"●","mass":"●","clamp stand":"┐","stopwatch":"◷","pendulum":"◯","meter rule":"📏","convex lens":"◉","lens":"◉","screen":"▯","ray box":"✦","glass block":"▱","protractor":"∠","beaker":"♜","conical flask":"⚗","burette":"▥","pipette":"◡","indicator":"●","dropper":"💧","test tube":"▯","thermometer":"°","tripod":"△","wire gauze":"▤","bunsen burner":"♨","heater":"♨","funnel":"▽","filter paper":"□","gas syringe":"▥","pressure sensor":"P","electrodes":"⊕","switch":"⏻","microscope":"◎","microscope slide":"▭","coverslip":"▱","stain":"●","petri dish":"◉","plant sample":"🌿","leaf":"🌿","potometer":"▥","quadrat":"□","soil sample":"◆","ph meter":"pH","data sheet":"▤","standard laboratory apparatus":"⚗","measuring instruments":"▤"};
const icon=n=>{n=n.toLowerCase();const k=Object.keys(apparatusIcons).find(x=>n.includes(x));return apparatusIcons[k]||"●"};
const fallback={Physics:["DC power supply","Ammeter","Voltmeter","Connecting wires"],Chemistry:["Beaker","Conical flask","Measuring cylinder","Thermometer"],Biology:["Microscope","Microscope slide","Coverslip","Plant sample"],Environmental:["Quadrat","Soil sample","Measuring instruments","Data sheet"]};
const formula=e=>{const t=e.type,a=+S.values[0]||0,b=+S.values[1]||0;switch(t){case"ohm":return a/(b||1);case"series":return a/(b+20);case"parallel":return a/(b||1);case"resistivity":return .0175*a/(Math.PI*Math.pow(b/2000,2));case"power":return a*a/(b||1);case"density":return a/(b||1);case"hooke":return a/(b||1);case"pendulum":return 2*Math.PI*Math.sqrt(Math.max(.01,a/100));case"moments":case"friction":return a*b;case"lens":return a===b?Infinity:a*b/(a-b);case"refraction":return Math.asin(Math.sin(a*Math.PI/180)/(b||1))*180/Math.PI;case"thermal":return a*50;case"gas":return a?b*100/a:0;default:return(a+b)/2}};
const ranges=n=>{n=n.toLowerCase();if(n.includes("ph"))return[1,14,.1,7];if(n.includes("angle"))return[0,85,1,30];if(n.includes("temperature"))return[5,90,1,25];if(n.includes("voltage"))return[0,12,.1,6];if(n.includes("resistance"))return[1,100,1,20];if(n.includes("mass"))return[1,500,1,50];if(/length|distance|height|diameter|volume/.test(n))return[1,100,.1,20];if(n.includes("time"))return[1,120,1,10];return[0,100,.1,20]};
const req=e=>[...new Set((e.materials&&e.materials.length?e.materials:fallback[e.subject]||fallback.Physics).filter(Boolean))].slice(0,8);
const newState=e=>({setup:[],values:(e.controls||["Variable A","Variable B"]).slice(0,2).map((n,i)=>ranges(n)[3]),rows:[],running:false,paused:false,elapsed:0,completed:false});
function toast(t){const x=$("#toast");if(!x)return;x.textContent=t;x.classList.add("show");clearTimeout(window.__slsV3Toast);window.__slsV3Toast=setTimeout(()=>x.classList.remove("show"),1800)}
function save(completed){const a=store.attempts[current.id]||{attempts:0,completed:0,history:[]};a.attempts++;if(completed)a.completed++;a.history=(a.history||[]).slice(-19);a.history.push({date:new Date().toISOString(),setup:S.setup,values:S.values,rows:S.rows});store.attempts[current.id]=a;if(completed)store.xp=(store.xp||0)+75;localStorage.setItem(KEY,JSON.stringify(store))}
function setupOK(){const have=S.setup.map(x=>x.toLowerCase());return req(current).every(r=>have.some(h=>h===r.toLowerCase()||h.includes(r.toLowerCase())||r.toLowerCase().includes(h)))}
function renderTray(){const tray=$("#apparatusTray"),placed=$("#placedApparatus"),items=req(current);if(!tray||!placed)return;
tray.innerHTML='<div class="apparatus-tray-head"><div><label>APPARATUS DRAWER</label><strong>Build the experiment yourself</strong><small>Drag equipment onto the bench, or click to place</small></div><button id="clearSetup" class="setup-clear">Clear setup</button></div><div class="apparatus-items">'+items.map((n,i)=>'<button class="apparatus-item" draggable="true" data-i="'+i+'"><span class="apparatus-icon">'+icon(n)+'</span><span><b>'+esc(n)+'</b><small>REQUIRED</small></span><i>↗</i></button>').join("")+'</div><div class="setup-progress">'+S.setup.length+" / "+items.length+" required apparatus placed</div>";
placed.innerHTML=S.setup.map((n,i)=>'<div class="placed-item" data-i="'+i+'"><span>'+icon(n)+'</span><b>'+esc(n)+'</b><button data-remove="'+i+'">×</button></div>').join("");
$("#benchDropHint")?.classList.toggle("hidden",S.setup.length>0);
const place=n=>{if(!S.setup.includes(n)){S.setup.push(n);renderTray();renderStatus();toast(n+" placed on the bench")}else toast(n+" is already placed")};
tray.querySelectorAll(".apparatus-item").forEach(b=>{const n=items[+b.dataset.i];b.onclick=()=>place(n);b.ondragstart=e=>e.dataTransfer.setData("text/plain",n)});
placed.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{S.setup.splice(+b.dataset.remove,1);renderTray();renderStatus()});
const bench=$(".bench");if(bench){bench.ondragover=e=>{e.preventDefault();bench.classList.add("drag-over")};bench.ondragleave=()=>bench.classList.remove("drag-over");bench.ondrop=e=>{e.preventDefault();bench.classList.remove("drag-over");const n=e.dataTransfer.getData("text/plain");if(n)place(n)}}
$("#clearSetup")?.addEventListener("click",()=>{S.setup=[];renderTray();renderStatus();toast("Bench cleared")})}
function renderControls(){const box=$("#controls");if(!box)return;const cs=(current.controls&&current.controls.length?current.controls:["Variable A","Variable B"]).slice(0,2);box.innerHTML='<div class="panel-head"><div><label>EXPERIMENT CONTROLS</label><h3>Live variables</h3></div><small>SIMULATION</small></div>'+cs.map((n,i)=>{const r=ranges(n);return'<div class="control"><label><span>'+esc(n)+'</span><output id="v3out'+i+'">'+S.values[i]+'</output></label><input class="range v3range" data-i="'+i+'" type="range" min="'+r[0]+'" max="'+r[1]+'" step="'+r[2]+'" value="'+S.values[i]+'"><small class="control-unit">'+esc(current.units?.[i]||"")+'</small></div>'}).join("")+'<div class="setup-note"><b>Required setup</b><span>'+S.setup.length+" / "+req(current).length+" apparatus</span></div>";
$$(".v3range").forEach(x=>x.oninput=()=>{S.values[+x.dataset.i]=+x.value;$("#v3out"+x.dataset.i).textContent=x.value;renderReadings();renderObservation()})}
function renderReadings(){const b=$("#readings");if(!b)return;const r=formula(current);b.innerHTML='<div class="reading"><small>'+esc(current.controls?.[0]||"Variable A")+'</small><strong>'+Number(S.values[0]).toFixed(2)+'</strong><em>'+esc(current.units?.[0]||"")+'</em></div><div class="reading"><small>'+esc(current.controls?.[1]||"Variable B")+'</small><strong>'+Number(S.values[1]).toFixed(2)+'</strong><em>'+esc(current.units?.[1]||"")+'</em></div><div class="reading-result"><small>Calculated result</small><strong>'+ (Number.isFinite(r)?r.toFixed(3):"∞")+'</strong><em>from live apparatus state</em></div>'}
function renderTable(){const h=$("#thead"),b=$("#tbody");if(!h||!b)return;const cols=current.columns?.length?current.columns:["Trial","Variable A","Variable B","Result"];h.innerHTML=cols.map(x=>"<th>"+esc(x)+"</th>").join("")+"<th>Action</th>";b.innerHTML=S.rows.map((r,i)=>"<tr>"+r.map(v=>"<td>"+esc(v)+"</td>").join("")+'<td><button class="row-delete" data-i="'+i+'">Delete</button></td></tr>').join("");b.querySelectorAll(".row-delete").forEach(x=>x.onclick=()=>{S.rows.splice(+x.dataset.i,1);renderTable();renderStatus()});$("#progress").style.width=Math.min(S.rows.length/3*100,100)+"%";$("#progressText").textContent=S.rows.length+" / 3 readings";$("#missionState").textContent=S.rows.length>=3?"READY TO FINISH":"IN PROGRESS"}
function renderObservation(){const x=$("#liveObservation");if(x)x.textContent=!setupOK()?"Place every required apparatus on the bench before starting.":S.running&&!S.paused?"The apparatus is active. Change a variable, observe the live response, and record evidence.":S.rows.length?"You have evidence. Change a variable and repeat the measurement to compare results.":"Setup complete. Start the experiment, then take repeated measurements.";const c=$("#observationClock");if(c)c.textContent=S.elapsed.toFixed(1)+" s"}
function renderStatus(){const x=$("#experimentStatus");if(x)x.innerHTML="<span>●</span><b>"+(S.completed?"COMPLETE":S.running?(S.paused?"PAUSED":"RUNNING"):(setupOK()?"READY":"SETUP REQUIRED"))+"</b><small>"+(setupOK()?"Operate the apparatus":"Place the required apparatus")+"</small>";renderObservation();renderReadings();renderTable();renderTray()}
function start(){if(!setupOK()){toast("Complete the required apparatus setup first");return}S.running=true;S.paused=false;renderStatus();toast("Experiment started")}
function record(){if(!setupOK()){toast("Complete the apparatus setup first");return}if(!S.running){toast("Start the experiment first");return}S.rows.push([String(S.rows.length+1),Number(S.values[0]).toFixed(2),Number(S.values[1]).toFixed(2),Number(formula(current)).toFixed(3)]);store.xp=(store.xp||0)+15;localStorage.setItem(KEY,JSON.stringify(store));renderStatus();toast("Reading recorded")}
function finish(){if(!setupOK()){toast("Complete the apparatus setup first");return}if(S.rows.length<3){toast("Record at least 3 measurements before analysing");return}S.completed=true;save(true);const box=$("#completionPanel");if(box){box.hidden=false;box.innerHTML='<div class="complete-burst">✓</div><label>EXPERIMENT COMPLETE</label><h2>'+esc(current.name)+'</h2><p><b>Objective:</b> '+esc(current.objective)+'</p><p><b>Evidence:</b> '+S.rows.length+' measurements recorded.</p><p><b>Final result:</b> '+Number(formula(current)).toFixed(3)+'</p><p><b>Conclusion:</b> '+esc(current.mission||"Use your recorded evidence to support your conclusion.")+'</p><div class="xp-award">+75 XP</div>'}renderProgress();toast("Experiment complete · +75 XP")}
function reset(){S=newState(current);$("#completionPanel")?.setAttribute("hidden","");renderAll();toast("Experiment reset")}
function renderAll(){if(!current)return;$("#activeName").textContent=current.name;$("#meta").textContent=(current.level===1?"BEGINNER":current.level===2?"INTERMEDIATE":"ADVANCED")+" · "+current.subject;$("#title").textContent=current.name;$("#objective").textContent=current.objective;$("#subject").textContent=current.subject;$("#level").textContent="LEVEL "+current.level;$("#mission").textContent=current.mission||"Collect and analyse evidence";$("#missionText").textContent=current.text||"Use the apparatus, record observations and analyse the evidence.";$("#experimentCount").textContent=String(E.length).padStart(2,"0");renderControls();renderReadings();renderStatus();$("#apparatus").innerHTML='<div class="generic-bench"><strong>'+esc(current.icon||"⚗")+" "+esc(current.name)+'</strong><small>LIVE SIMULATION · BUILD THE SETUP BELOW</small></div>';renderTray();$$(".lab-steps span").forEach((x,i)=>x.classList.toggle("active",i<=(setupOK()?(S.rows.length?3:S.running?2:1):0)))}
function load(e){current=e;S=newState(e);show("lab");renderAll()}
function show(v){const id=v==="progress"?"progressView":v;$$(".view").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#crumb").textContent={lab:"Laboratory",library:"Experiment Library",notebook:"My Notebook",progress:"Progress"}[v]||"Laboratory";if(v==="library")library();if(v==="notebook")notebook();if(v==="progress")renderProgress()}
function library(){const cards=$("#cards"),filters=$("#filters"),search=$("#search");if(!cards)return;let f="All";if(filters)filters.innerHTML=["All",...new Set(E.map(e=>e.subject))].map(x=>'<button class="filter '+(x==="All"?"active":"")+'" data-f="'+esc(x)+'">'+esc(x)+"</button>").join("");const draw=()=>{const q=(search?.value||"").toLowerCase();cards.innerHTML=E.filter(e=>(f==="All"||e.subject===f)&&(!q||[e.name,e.subject,e.objective].join(" ").toLowerCase().includes(q))).map(e=>'<button class="experiment-card" data-id="'+esc(e.id)+'"><div class="card-icon">'+esc(e.icon||"⚗")+'</div><div><label>'+esc(e.subject)+' · LEVEL '+e.level+'</label><h3>'+esc(e.name)+'</h3><p>'+esc(e.objective)+'</p><small>'+(store.attempts?.[e.id]?.completed||0)+' completed · '+req(e).length+' required apparatus</small></div></button>').join("");cards.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>load(E.find(e=>e.id===x.dataset.id)))};filters?.querySelectorAll("[data-f]").forEach(x=>x.onclick=()=>{f=x.dataset.f;filters.querySelectorAll("[data-f]").forEach(b=>b.classList.toggle("active",b===x));draw()});if(search)search.oninput=draw;draw()}
function notebook(){const p=$("#paper");if(!p)return;const a=[];Object.entries(store.attempts||{}).forEach(([id,v])=>{const e=E.find(x=>x.id===id);(v.history||[]).forEach(h=>a.push({e,h}))});a.sort((x,y)=>new Date(y.h.date)-new Date(x.h.date));p.innerHTML=a.length?a.slice(0,30).map(x=>'<article class="notebook-entry"><label>'+esc(x.e.subject)+' · '+new Date(x.h.date).toLocaleString()+'</label><h3>'+esc(x.e.name)+'</h3><p>'+esc(x.e.objective)+'</p><div><b>'+x.h.rows.length+'</b> readings · <b>'+x.h.setup.length+'</b> apparatus placed</div></article>').join(""):'<div class="empty-state"><h3>Your notebook is empty</h3><p>Completed attempts are saved locally and appear here.</p></div>'}
function renderProgress(){const b=$("#progressCards"),r=$("#roadmap");if(!b||!r)return;const completed=Object.values(store.attempts||{}).reduce((n,a)=>n+(a.completed||0),0),attempted=Object.keys(store.attempts||{}).length;b.innerHTML='<div><span>Experiments completed</span><b>'+completed+'</b></div><div><span>Experiments attempted</span><b>'+attempted+'</b></div><div><span>XP</span><b>'+Number(store.xp||0)+'</b></div>';r.innerHTML=["Physics","Chemistry","Biology","Environmental"].map(s=>{const all=E.filter(e=>e.subject===s),done=all.filter(e=>store.attempts?.[e.id]?.completed).length;return'<div><span>'+s+'</span><b>'+done+' / '+all.length+'</b><div class="progress"><span style="width:'+Math.round(done/Math.max(1,all.length)*100)+'%"></span></div></div>'}).join("")}
function bind(id,fn){const el=$(id);if(!el)return;const n=el.cloneNode(true);el.replaceWith(n);n.addEventListener("click",fn)}
bind("#reset",reset);bind("#finish",finish);bind("#record",record);bind("#clearRows",()=>{S.rows=[];renderStatus();toast("Measurements cleared")});bind("#whyBtn",()=>{const p=$("#whyPanel");if(p){p.hidden=!p.hidden;p.innerHTML="<b>Why did this happen?</b><p>"+esc(current.objective)+"</p><p><strong>Scientific basis:</strong> "+esc(current.mission||"Compare the evidence from repeated measurements.")+"</p>"}});
$$(".nav").forEach(n=>n.onclick=()=>show(n.dataset.view));$("#newBtn")?.addEventListener("click",()=>load(E[0]));
timer=setInterval(()=>{if(S?.running&&!S.paused){S.elapsed+=.1;renderObservation()}},100);
window.__ScienceLabV3={load,reset,record,finish,state:()=>S};
library();renderProgress();load(E[0]);
})();